#!/bin/sh

docker run \
  --rm \
  --name transcoder \
  --detach \
  --mount "type=bind,src=/volume1/Media/Pending,dst=/input" \
  --mount "type=bind,src=/volume1/Media/Staging,dst=/output" \
  --restart always \
  dathan/transcoder-service
